### PR TITLE
Add CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by ChristopherBrown200**
Please review CODE_OF_CONDUCT.md and leave any comments or concerns on this draft pull request.

### CODE REVIEW

**Review by Guacamole-Dog — APPROVED** [review]
Looks good as a baseline, and we might not even need to add anything to it.

**Review by Reece3210 — APPROVED** [review]
Looks all good to me

**Comment by philomina-1** [comment]
Beautiful Code of Conduct document. I don't even think it needs to be updated in any way ... but if we wanted to, we could add personal ideas as to how we can achieve success as a group.

**Review by philomina-1 — APPROVED** [review]
Template perfectly encompasses all of the ideas I think we'll be utilizing as we work together on this project. Can't think of any changes to make!

**Review by derek-munday — APPROVED** [review]

**Pull request merged**
